<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>Suricate Profile</string>
        <key>scopeName</key>
        <string>source.suricate-profile</string>
        <key>fileTypes</key>
        <array>
            <string>suricate-profile</string>
        </array>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>source.json</string>
            </dict>
        </array>
    </dict>
</plist>
